models:
  - display_name: "Gemma3:1b"
    model_id: "gemma3:1b"
  - display_name: "Moondream 2"
    model_id: "moondream"
  - display_name: "Qwen3:0.6b"
    model_id: "qwen3:0.6b"

default_prompt: |
  You are an AI assistant that provides concise and direct answers.
  Answer the following question without explanation or reasoning.
  Give only the specific answer.

files:
  question_file_name: "question_"
  question_file_extension: ".txt"

folders:
  data_folder_name: "../data/questions/exercises1"
  experiment_folder_name: "run_"

paths:
  base_experiments_folder: "../data/runs"
