ollama:
  base_url: "http://localhost:11434/"
  api_key: "ollama"

models:
  - display_name: "DeepSeek R1:1.5b"
    model_id: "deepseek-r1:1.5b"      # 1.1 GB
  - display_name: "Deepseek-r1"
    model_id: "deepseek-r1"           # 4.7 GB
  - display_name: "Gemma3:1b"
    model_id: "gemma3:1b"             # 815 MB
  - display_name: "Llama3.2:1b"
    model_id: "llama3.2:1b"           # 1.3 GB
    display_name: "Mistrallite:7b"
    model_id: "mistrallite:7b"        # 4.1 GB
  - display_name: "Moondream 2"
    model_id: "moondream:1.8b"        # 1.7 GB
  - display_name: "Phi3:3.8b"
    model_id: "phi3:3.8b"             # 2.2 GB
  - display_name: "smollm2:1.7b"
    model_id: "smollm2:1.7b"          # 1.8 GB
  - display_name: "TinyLlama:1.1b"
    model_id: "tinyllama:1.1b"        # 638 MB
  - display_name: "Qwen3:0.6b"
    model_id: "qwen3:0.6b"            # 523 MB

# Valid question_types:
# - open_answer
# - multiple_choice
question_type: "multiple_choice"

# Valid model modes
# - chat
# - generate
model_mode: "generate"

prompts:
  open_answer_questions: |
    You are an AI assistant that provides concise and direct answers.
    Answer the following question without explanation or reasoning.
    Give only the specific answer.

  multiple_choice_questions: |
    You are an AI assistant that answers multiple-choice questions.
    You must respond with exactly one of the following options: [a], [b], [c], [d], [e], or [f].
    Your response must match the format of the options exactly, including brackets and lowercase letters.
    Do not include any explanation, commentary, or additional text—only the selected option.

folders:
  data_folder_name: "../data/questions/exercises1_all"
  base_experiments_folder: "../data/runs"
  experiment_folder_name: "run_"

files:
  question_file_name: "question_"
  question_file_extension: ".txt"

num_runs_per_question: 10